# Generated by Django 5.0.6 on 2024-07-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='submit_time',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
