# Generated by Django 5.0.6 on 2024-07-22 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_mcq_correct_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='response',
            name='description',
        ),
        migrations.RemoveField(
            model_name='response',
            name='mcq',
        ),
    ]
