# Generated by Django 5.0.6 on 2024-07-22 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_response_answer_remove_response_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcq',
            name='correct_answer',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='response',
            name='submit_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
