# Generated by Django 5.0.6 on 2024-07-22 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_mcq_correct_answer_alter_response_submit_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcq',
            name='correct_answer',
            field=models.CharField(max_length=200),
        ),
    ]
